config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :departments
  resources :teachers
  resources :students
  resources :universities
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    # @teacher = Teacher.new(teacher_params)
    @departamento=Department.find(params[:teacher][:department_id])
    @teacher=@departamento.teachers.create(teacher_params)  
    respond_to do |format|
      if @teacher!=nil
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def teacher_params
      params.require(:teacher).permit(:codigo, :nombre, :direccion, :telefono, :titulo_profesional, :nivel_estudios, :department_id)
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field col s3">
      <%= form.label :codigo %>
      <%= form.text_field :codigo, id: :teacher_codigo %>
    </div>

    <div class="field col s3">
      <%= form.label :nombre %>
      <%= form.text_field :nombre, id: :teacher_nombre %>
    </div>

    <div class="field col s3">
      <%= form.label :direccion %>
      <%= form.text_field :direccion, id: :teacher_direccion %>
    </div>

    <div class="field col s3">
      <%= form.label :telefono %>
      <%= form.text_field :telefono, id: :teacher_telefono %>
    </div>
  </div>

  <div class="row">
    <div class="field col s4">
      <%= form.label :titulo_profesional %>
      <%= form.text_field :titulo_profesional, id: :teacher_titulo_profesional %>
    </div>

    <div class="field col s4">
      <%= form.label :nivel_estudios %>
      <%= form.text_field :nivel_estudios, id: :teacher_nivel_estudios %>
    </div>

    <div class="input-field col s4">
      <%= form.collection_select(:department_id,Department.all,:id,:nombre,
                                {:prompt=>"Departamentos",:select=>@teacher.department_id},
                                {class: 'form-control'}) %>
    </div>
  </div>

  <div class="row">
    <div class="field col s12">

    </div>
  </div>

  <div class="row">
    <div class="waves-effect waves-light btn">
      <%= form.submit "GUARDAR"%>
    </div>

    <div class="waves-effect waves-light btn">
      <%= link_to 'Regresar', teachers_path, {:style=>'color: #000000'} %>
    </div>
  </div>

<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Docentes</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Titulo profesional</th>
      <th>Nivel estudios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.codigo %></td>
        <td><%= teacher.nombre %></td>
        <td><%= teacher.direccion %></td>
        <td><%= teacher.telefono %></td>
        <td><%= teacher.titulo_profesional %></td>
        <td><%= teacher.nivel_estudios %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h2>Nuevo Docente</h2><br>

<%= render 'form', teacher: @teacher %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @teacher.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @teacher.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @teacher.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @teacher.telefono %>
</p>

<p>
  <strong>Titulo profesional:</strong>
  <%= @teacher.titulo_profesional %>
</p>

<p>
  <strong>Nivel estudios:</strong>
  <%= @teacher.nivel_estudios %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>