config/routes.rb
Rails.application.routes.draw do
  resources :courses
  resources :departments
  resources :teachers
  resources :students
  resources :universities
  devise_for :users
  get 'welcome/index'
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/university.rb
class University < ApplicationRecord
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
  before_action :set_university, only: [:show, :edit, :update, :destroy]

  # GET /universities
  # GET /universities.json
  def index
    @universities = University.all
  end

  # GET /universities/1
  # GET /universities/1.json
  def show
  end

  # GET /universities/new
  def new
    @university = University.new
  end

  # GET /universities/1/edit
  def edit
  end

  # POST /universities
  # POST /universities.json
  def create
    @university = University.new(university_params)

    respond_to do |format|
      if @university.save
        format.html { redirect_to @university, notice: 'University was successfully created.' }
        format.json { render :show, status: :created, location: @university }
      else
        format.html { render :new }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /universities/1
  # PATCH/PUT /universities/1.json
  def update
    respond_to do |format|
      if @university.update(university_params)
        format.html { redirect_to @university, notice: 'University was successfully updated.' }
        format.json { render :show, status: :ok, location: @university }
      else
        format.html { render :edit }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /universities/1
  # DELETE /universities/1.json
  def destroy
    @university.destroy
    respond_to do |format|
      format.html { redirect_to universities_url, notice: 'University was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_university
      @university = University.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def university_params
      params.require(:university).permit(:codigo, :nombre, :direccion, :telefono, :codigo_postal)
    end
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/universities/_form.html.erb
<%= form_with(model: university, local: true) do |form| %>
  <% if university.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(university.errors.count, "error") %> prohibited this university from being saved:</h2>

      <ul>
      <% university.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo, id: :university_codigo %>
  </div>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :university_nombre %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion, id: :university_direccion %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.text_field :telefono, id: :university_telefono %>
  </div>

  <div class="field">
    <%= form.label :codigo_postal %>
    <%= form.text_field :codigo_postal, id: :university_codigo_postal %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/universities/edit.html.erb
<h1>Editing University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Show', @university %> |
<%= link_to 'Back', universities_path %>

app/views/universities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Universidades</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Codigo postal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @universities.each do |university| %>
      <tr>
        <td><%= university.codigo %></td>
        <td><%= university.nombre %></td>
        <td><%= university.direccion %></td>
        <td><%= university.telefono %></td>
        <td><%= university.codigo_postal %></td>
        <td><%= link_to 'Show', university %></td>
        <td><%= link_to 'Edit', edit_university_path(university) %></td>
        <td><%= link_to 'Destroy', university, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New University', new_university_path %>

app/views/universities/new.html.erb
<h1>New University</h1>

<%= render 'form', university: @university %>

<%= link_to 'Back', universities_path %>

app/views/universities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @university.codigo %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @university.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @university.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @university.telefono %>
</p>

<p>
  <strong>Codigo postal:</strong>
  <%= @university.codigo_postal %>
</p>

<%= link_to 'Edit', edit_university_path(@university) %> |
<%= link_to 'Back', universities_path %>